//
// Generated file, do not edit! Created by nedtool 5.4 from AppMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __COSC418ASSIGNMENT_APPMESSAGE_M_H
#define __COSC418ASSIGNMENT_APPMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace cosc418assignment {

/**
 * Class generated from <tt>AppMessage.msg:4</tt> by nedtool.
 * <pre>
 * packet AppMessage
 * {
 *     simtime_t timeStamp;
 *     int senderId;
 *     int seqno;
 *     int messageSize;
 * }
 * </pre>
 */
class AppMessage : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t timeStamp;
    int senderId;
    int seqno;
    int messageSize;

  private:
    void copy(const AppMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppMessage&);

  public:
    AppMessage(const char *name=nullptr, short kind=0);
    AppMessage(const AppMessage& other);
    virtual ~AppMessage();
    AppMessage& operator=(const AppMessage& other);
    virtual AppMessage *dup() const override {return new AppMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getTimeStamp() const;
    virtual void setTimeStamp(::omnetpp::simtime_t timeStamp);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getSeqno() const;
    virtual void setSeqno(int seqno);
    virtual int getMessageSize() const;
    virtual void setMessageSize(int messageSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppMessage& obj) {obj.parsimUnpack(b);}

} // namespace cosc418assignment

#endif // ifndef __COSC418ASSIGNMENT_APPMESSAGE_M_H

